name: Run Experiments

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset'
        required: true
        default: 'dataset_sample'

jobs:
  run-experiment:
    timeout-minutes: 4320
    runs-on: [self-hosted]
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Update in secrets txt
      run: |
        echo ${{ secrets.PAT }} > ./secrets/github-pat.txt
        echo ${{ secrets.OPENAI_API }} > ./secrets/api-key.txt
      working-directory: ./experiments

    - name: Run python script
      run: |
        pip install -r requirements.txt
        python3 run_experiment.py ${{ github.event.inputs.dataset }}
      working-directory: ./experiments

    - name: Publish output.csv
      uses: actions/upload-artifact@v2
      with:
        name: output.csv
        path: experiments/dataset/output.csv